#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WF.Player.Droid.Resource", IsApplication=true)]

namespace WF.Player.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.XamForms.Mobile.Droid.Resource.String.ApplicationName = global::WF.Player.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.Mobile.Droid.Resource.String.Hello = global::WF.Player.Droid.Resource.String.Hello;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::WF.Player.Droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::WF.Player.Droid.Resource.String.Hello;
			global::WF.Player.Core.Resource.String.library_name = global::WF.Player.Droid.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050004
			public const int image_size_key = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int image_size_value = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int pref_sensor_orientation_filter_key = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int pref_sensor_orientation_filter_value = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int text_alignment_key = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int text_alignment_value = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int theme_key = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_value = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HomeIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IconAccuracyDark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IconAccuracyLight = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IconAltitudeDark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IconAltitudeLight = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IconEmpty = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IconInventory = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IconLocation = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IconMap = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IconMenu = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IconNumber = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IconOverview = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IconPlay = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IconResume = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IconRouting = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IconSmall = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IconTasks = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Splash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int SplashScaled = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int myButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int text_size = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PreferencesView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040032
			public const int Vernacular_P0_Actions = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int Vernacular_P0_Alignment = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int Vernacular_P0_Alignmentoftext = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int Vernacular_P0_Attributes = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int Vernacular_P0_Autochange = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int Vernacular_P0_Blue = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int Vernacular_P0_By = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int Vernacular_P0_Cancel = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int Vernacular_P0_Cartridges = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int Vernacular_P0_Centeralign = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int Vernacular_P0_Choose = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int Vernacular_P0_CommentSavefile = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int Vernacular_P0_CurrentAccuracy101230125 = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int Vernacular_P0_CurrentCoordinates101230125 = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int Vernacular_P0_Dark = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int Vernacular_P0_Description = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int Vernacular_P0_Details = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int Vernacular_P0_E = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int Vernacular_P0_Feedback = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int Vernacular_P0_Filterappliedtoorientation46Strongerfiltercauseslowerreactions44butfluentmovement46 = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int Vernacular_P0_Focus = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int Vernacular_P0_Focusinputfieldwhendialogappears = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int Vernacular_P0_Fontsize = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int Vernacular_P0_Fontsizeofdialogtext = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int Vernacular_P0_Fontsizeoftextinsp46Defaultis1846 = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int Vernacular_P0_Formuchfunwiththecartridge44youshouldwaitforagoodaccuracyofyourGPSsignal46 = 2130968651;
			
			// aapt resource value: 0x7f04004d
			public const int Vernacular_P0_GPSCheck = 2130968653;
			
			// aapt resource value: 0x7f04004c
			public const int Vernacular_P0_GameMenu = 2130968652;
			
			// aapt resource value: 0x7f04004e
			public const int Vernacular_P0_Halfheightofscreen = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int Vernacular_P0_Heavyfilter = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int Vernacular_P0_HelloWorld44ClickMe33 = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int Vernacular_P0_History = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int Vernacular_P0_Ifenabledusetruebearing46Otherwiseusemagneticbearing46 = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int Vernacular_P0_Image = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int Vernacular_P0_Input = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int Vernacular_P0_Inside = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int Vernacular_P0_Inventory = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int Vernacular_P0_Leftalign = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int Vernacular_P0_Light = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int Vernacular_P0_Lightfilter = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int Vernacular_P0_Loading464646 = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int Vernacular_P0_Logs = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int Vernacular_P0_Map = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int Vernacular_P0_Mediumfilter = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int Vernacular_P0_N = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int Vernacular_P0_No = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int Vernacular_P0_Nodescriptionavailable = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int Vernacular_P0_Nofilter = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int Vernacular_P0_Noitems = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int Vernacular_P0_Nomapavailable = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int Vernacular_P0_Nonewtasks = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int Vernacular_P0_Noresize = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int Vernacular_P0_Nothingofinterest = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int Vernacular_P0_Ok = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int Vernacular_P0_Orientationfilter = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int Vernacular_P0_Overview = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int Vernacular_P0_Playasoundeachtimeabuttonispressed = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int Vernacular_P0_Pleasewait464646 = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int Vernacular_P0_Provideacommenttoidentifythissavefile = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int Vernacular_P0_Quit = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int Vernacular_P0_Resize = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int Vernacular_P0_Resizeimagewhendisplaying = 2130968687;
			
			// aapt resource value: 0x7f040070
			public const int Vernacular_P0_Rightalign = 2130968688;
			
			// aapt resource value: 0x7f040071
			public const int Vernacular_P0_S = 2130968689;
			
			// aapt resource value: 0x7f040072
			public const int Vernacular_P0_Save = 2130968690;
			
			// aapt resource value: 0x7f040073
			public const int Vernacular_P0_SaveGame = 2130968691;
			
			// aapt resource value: 0x7f040074
			public const int Vernacular_P0_Sensors = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int Vernacular_P0_Settings = 2130968693;
			
			// aapt resource value: 0x7f040076
			public const int Vernacular_P0_Shrinktowidthofscreen = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int Vernacular_P0_Sound = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int Vernacular_P0_Speedvalue = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int Vernacular_P0_Start = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int Vernacular_P0_Startanyway = 2130968698;
			
			// aapt resource value: 0x7f04007b
			public const int Vernacular_P0_Tasks = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int Vernacular_P0_Text = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int Vernacular_P0_Theme = 2130968701;
			
			// aapt resource value: 0x7f04007e
			public const int Vernacular_P0_Themeforthisapp40onlyupdatedafterarestartoftheapp41 = 2130968702;
			
			// aapt resource value: 0x7f04007f
			public const int Vernacular_P0_Unknown = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int Vernacular_P0_Usehardwarecompass = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int Vernacular_P0_Usehardwarecompassformaprotationandcompassscreen46BearingfromGPS40betterforcar41willbeusedifdisabled46 = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int Vernacular_P0_Usesourceforbearingdefinedby34Usehardwarecompass34settingsforlowspeed46ForhighspeedusebearingfromGPS46 = 2130968706;
			
			// aapt resource value: 0x7f040083
			public const int Vernacular_P0_Usetruebearing = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int Vernacular_P0_Valuethatdefinewhichsourceforbearingwillbeused40lowspeedbelowthisvalue44highspeedabovethisvalue4146 = 2130968708;
			
			// aapt resource value: 0x7f040085
			public const int Vernacular_P0_Vibrate = 2130968709;
			
			// aapt resource value: 0x7f040086
			public const int Vernacular_P0_Vibrateeachtimeabuttonispressed = 2130968710;
			
			// aapt resource value: 0x7f040087
			public const int Vernacular_P0_W = 2130968711;
			
			// aapt resource value: 0x7f040088
			public const int Vernacular_P0_WF46Player46Android = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int Vernacular_P0_Widthofscreen = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int Vernacular_P0_Wouldyouliketosavethecurrentgame63 = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int Vernacular_P0_Writeyourinputhere464646 = 2130968715;
			
			// aapt resource value: 0x7f04008c
			public const int Vernacular_P0_Yes = 2130968716;
			
			// aapt resource value: 0x7f04008d
			public const int Vernacular_P0_YouSee = 2130968717;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int pref_feedback = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int pref_feedback_sound = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int pref_feedback_sound_detail = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int pref_feedback_vibration = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int pref_feedback_vibration_detail = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int pref_header = 2130968581;
			
			// aapt resource value: 0x7f04001c
			public const int pref_image = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int pref_image_size = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int pref_image_size_detail = 2130968606;
			
			// aapt resource value: 0x7f040022
			public const int pref_image_size_height = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int pref_image_size_noresize = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int pref_image_size_shrink = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int pref_image_size_width = 2130968609;
			
			// aapt resource value: 0x7f040019
			public const int pref_input = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int pref_input_focus = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int pref_input_focus_detail = 2130968603;
			
			// aapt resource value: 0x7f04002c
			public const int pref_sensor_orientation_filter = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int pref_sensor_orientation_filter_detail = 2130968621;
			
			// aapt resource value: 0x7f040031
			public const int pref_sensor_orientation_filter_heavy = 2130968625;
			
			// aapt resource value: 0x7f04002f
			public const int pref_sensor_orientation_filter_light = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int pref_sensor_orientation_filter_medium = 2130968624;
			
			// aapt resource value: 0x7f04002e
			public const int pref_sensor_orientation_filter_none = 2130968622;
			
			// aapt resource value: 0x7f040023
			public const int pref_sensors = 2130968611;
			
			// aapt resource value: 0x7f04002a
			public const int pref_sensors_azimuth_true = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int pref_sensors_azimuth_true_detail = 2130968619;
			
			// aapt resource value: 0x7f040024
			public const int pref_sensors_hardware_compass = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int pref_sensors_hardware_compass_auto_change = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int pref_sensors_hardware_compass_auto_change_detail = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int pref_sensors_hardware_compass_auto_change_value = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int pref_sensors_hardware_compass_auto_change_value_detail = 2130968617;
			
			// aapt resource value: 0x7f040025
			public const int pref_sensors_hardware_compass_detail = 2130968613;
			
			// aapt resource value: 0x7f040010
			public const int pref_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int pref_text_alignment = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int pref_text_alignment_center = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int pref_text_alignment_detail = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int pref_text_alignment_left = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int pref_text_alignment_right = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int pref_text_size = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int pref_text_size_detail = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int pref_text_size_dialog = 2130968600;
			
			// aapt resource value: 0x7f04000b
			public const int pref_theme = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int pref_theme_blue = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int pref_theme_dark = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int pref_theme_detail = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int pref_theme_light = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int AppTheme_Light = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
