#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("WF.Player.Droid.Resource", IsApplication=true)]

namespace WF.Player.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::WF.Player.Droid.Resource.Attribute.ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::WF.Player.Droid.Resource.Attribute.ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::WF.Player.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::WF.Player.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::WF.Player.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRadius = global::WF.Player.Droid.Resource.Attribute.ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::WF.Player.Droid.Resource.Attribute.ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::WF.Player.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::WF.Player.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahText = global::WF.Player.Droid.Resource.Attribute.ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::WF.Player.Droid.Resource.Attribute.ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::WF.Player.Droid.Resource.Attribute.ahTextSize;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::WF.Player.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::WF.Player.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbg = global::WF.Player.Droid.Resource.Drawable.roundedbg;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::WF.Player.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingImage = global::WF.Player.Droid.Resource.Id.loadingImage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::WF.Player.Droid.Resource.Id.loadingProgressBar;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::WF.Player.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Id.textViewStatus = global::WF.Player.Droid.Resource.Id.textViewStatus;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loading = global::WF.Player.Droid.Resource.Layout.loading;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingimage = global::WF.Player.Droid.Resource.Layout.loadingimage;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Layout.loadingprogress = global::WF.Player.Droid.Resource.Layout.loadingprogress;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.ApplicationName = global::WF.Player.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.Hello = global::WF.Player.Droid.Resource.String.Hello;
			global::Acr.XamForms.UserDialogs.Droid.Resource.String.library_name = global::WF.Player.Droid.Resource.String.library_name;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::WF.Player.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.XamForms.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::WF.Player.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::WF.Player.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::WF.Player.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::WF.Player.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::WF.Player.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::WF.Player.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::WF.Player.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::WF.Player.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::WF.Player.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::WF.Player.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::WF.Player.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::WF.Player.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::WF.Player.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::WF.Player.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::WF.Player.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::WF.Player.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::WF.Player.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::WF.Player.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::WF.Player.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::WF.Player.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::WF.Player.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::WF.Player.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::WF.Player.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::WF.Player.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::WF.Player.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::WF.Player.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Acr.XamForms.Mobile.Droid.Resource.String.ApplicationName = global::WF.Player.Droid.Resource.String.ApplicationName;
			global::Acr.XamForms.Mobile.Droid.Resource.String.Hello = global::WF.Player.Droid.Resource.String.Hello;
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::WF.Player.Droid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::WF.Player.Droid.Resource.String.Hello;
			global::WF.Player.Core.Resource.String.library_name = global::WF.Player.Droid.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050004
			public const int image_size_key = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int image_size_value = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int pref_sensor_orientation_filter_key = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int pref_sensor_orientation_filter_value = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int text_alignment_key = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int text_alignment_value = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int theme_key = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_value = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HomeIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_errorstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_successstatus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IconAccuracyDark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IconAccuracyLight = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IconAltitudeDark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IconAltitudeLight = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IconEmpty = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IconInventory = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int IconLocation = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IconMap = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int IconMenu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int IconNumber = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int IconPlay = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int IconResume = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int IconRouting = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int IconSmall = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int IconTask = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int IconYouSee = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int roundedbg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int roundedbgdark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Splash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int SplashScaled = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int loadingImage = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int loadingProgressBar = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int loadingProgressWheel = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int myButton = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int textViewStatus = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int text_size = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PreferencesView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int pref_feedback = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int pref_feedback_sound = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int pref_feedback_sound_detail = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int pref_feedback_vibration = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int pref_feedback_vibration_detail = 2130968586;
			
			// aapt resource value: 0x7f040005
			public const int pref_header = 2130968581;
			
			// aapt resource value: 0x7f04001c
			public const int pref_image = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int pref_image_size = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int pref_image_size_detail = 2130968606;
			
			// aapt resource value: 0x7f040022
			public const int pref_image_size_height = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int pref_image_size_noresize = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int pref_image_size_shrink = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int pref_image_size_width = 2130968609;
			
			// aapt resource value: 0x7f040019
			public const int pref_input = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int pref_input_focus = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int pref_input_focus_detail = 2130968603;
			
			// aapt resource value: 0x7f04002c
			public const int pref_sensor_orientation_filter = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int pref_sensor_orientation_filter_detail = 2130968621;
			
			// aapt resource value: 0x7f040031
			public const int pref_sensor_orientation_filter_heavy = 2130968625;
			
			// aapt resource value: 0x7f04002f
			public const int pref_sensor_orientation_filter_light = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int pref_sensor_orientation_filter_medium = 2130968624;
			
			// aapt resource value: 0x7f04002e
			public const int pref_sensor_orientation_filter_none = 2130968622;
			
			// aapt resource value: 0x7f040023
			public const int pref_sensors = 2130968611;
			
			// aapt resource value: 0x7f04002a
			public const int pref_sensors_azimuth_true = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int pref_sensors_azimuth_true_detail = 2130968619;
			
			// aapt resource value: 0x7f040024
			public const int pref_sensors_hardware_compass = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int pref_sensors_hardware_compass_auto_change = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int pref_sensors_hardware_compass_auto_change_detail = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int pref_sensors_hardware_compass_auto_change_value = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int pref_sensors_hardware_compass_auto_change_value_detail = 2130968617;
			
			// aapt resource value: 0x7f040025
			public const int pref_sensors_hardware_compass_detail = 2130968613;
			
			// aapt resource value: 0x7f040010
			public const int pref_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int pref_text_alignment = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int pref_text_alignment_center = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int pref_text_alignment_detail = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int pref_text_alignment_left = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int pref_text_alignment_right = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int pref_text_size = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int pref_text_size_detail = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int pref_text_size_dialog = 2130968600;
			
			// aapt resource value: 0x7f04000b
			public const int pref_theme = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int pref_theme_blue = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int pref_theme_dark = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int pref_theme_detail = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int pref_theme_light = 2130968590;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int AppTheme_Light = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
